# Generated by Django 3.0 on 2021-12-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suscriptores',
            new_name='Suscriptor',
        ),
    ]
