# Generated by Django 3.0 on 2021-12-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0002_auto_20211206_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='imagen_referencial',
            field=models.ImageField(upload_to='images/', verbose_name='Imagen referencial'),
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen_referencial',
            field=models.ImageField(max_length=255, upload_to='images/', verbose_name='Imagen referencial'),
        ),
    ]
