# Generated by Django 3.0 on 2021-12-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Principal', '0003_auto_20211209_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='imagen_referencial',
            field=models.ImageField(blank=True, null=True, upload_to='autores/', verbose_name='Imagen referencial'),
        ),
    ]
